<a href="https://colab.research.google.com/github/sandhyaparna/GCP-GoogleCloudPlatform/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf

# TensorFlow and Deep Learning fundamentals with Python videos
* https://www.youtube.com/watch?v=tpCFfeUEGs8&t=3221s
* https://github.com/mrdbourke/tensorflow-deep-learning
* https://colab.research.google.com/github/sandhyaparna/Python-DataScience-CookBook/blob/master/Tensorflow.ipynb



* tf.constant: shape & dimensions of tensors, mention data type
* tf.Varible: assign/modify values
* random tensor generator: uniform, normal distribution
* tf.ones(shape=(3, 2)); tf.zeros(shape=(3, 2))
* shuffle a tensor: shuffling is important for NN as we want the model to not see a continous flow of images of same category, it will impact how the model learns - matrix is shuffled based on rows
  * To shuffle in the same order: we need to Set the global random seed using tf.random.set_seed(42), before using it in ft.random.shuffle(matrix, seed=42)
* Turn arrays into tensors
* Indexing Tensors
* tf.cast(X, dtype=tf.float16) : change data type of tensor
* tf.abs(X)
* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.
* tf.argmax() - find the position of the maximum element in a given tensor.
* tf.argmin() - find the position of the minimum element in a given tensor.


* tf.function: use @tf.function before defining a function
* compare between different models
  * Tensor Board: https://tensorboard.dev/
  * Weights & Biases: https://wandb.ai/site
* model_name.save("path")
* 

| **Hyperparameter** | **Typical value** |
| --- | --- |
| Input layer shape | Same shape as number of features (e.g. 3 for # bedrooms, # bathrooms, # car spaces in housing price prediction) |
| Hidden layer(s) | Problem specific, minimum = 1, maximum = unlimited |
| Neurons per hidden layer | Problem specific, generally 10 to 100 |
| Output layer shape | Same shape as desired prediction shape (e.g. 1 for house price) |
| Hidden activation | Usually [ReLU](https://www.kaggle.com/dansbecker/rectified-linear-units-relu-in-deep-learning) (rectified linear unit) |
| Output activation | None, ReLU, logistic/tanh |
| Loss function | [MSE](https://en.wikipedia.org/wiki/Mean_squared_error) (mean square error) or [MAE](https://en.wikipedia.org/wiki/Mean_absolute_error) (mean absolute error)/Huber (combination of MAE/MSE) if outliers |
| Optimizer | [SGD](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD) (stochastic gradient descent), [Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) |

| **Hyperparameter** | **Binary Classification** | **Multiclass classification** |
| --- | --- | --- |
| Input layer shape | Same as number of features (e.g. 5 for age, sex, height, weight, smoking status in heart disease prediction) | Same as binary classification |
| Hidden layer(s) | Problem specific, minimum = 1, maximum = unlimited | Same as binary classification |
| Neurons per hidden layer | Problem specific, generally 10 to 100 | Same as binary classification |
| Output layer shape | 1 (one class or the other) | 1 per class (e.g. 3 for food, person or dog photo) |
| Hidden activation | Usually [ReLU](https://www.kaggle.com/dansbecker/rectified-linear-units-relu-in-deep-learning) (rectified linear unit) | Same as binary classification |
| Output activation | [Sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) | [Softmax](https://en.wikipedia.org/wiki/Softmax_function) |
| Loss function | [Cross entropy](https://en.wikipedia.org/wiki/Cross_entropy#Cross-entropy_loss_function_and_logistic_regression) ([`tf.keras.losses.BinaryCrossentropy`](https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy) in TensorFlow) | Cross entropy ([`tf.keras.losses.CategoricalCrossentropy`](https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy) in TensorFlow) |
| Optimizer | [SGD](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD) (stochastic gradient descent), [Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) | Same as binary classification |

In [3]:
import plotly.express as px
Tips = px.data.tips()
Tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
Tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
Tips['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [ ]:
Tips['sex'].value_counts(0)

Male      157
Female     87
Name: sex, dtype: int64

In [ ]:
Tips_copy = Tips
Tips_shallowcopy = Tips.copy()
Tips_deepcopy = Tips.copy(deep=True)

In [ ]:
Tips['tips_10perc_inc'] = Tips['tip']*1.1

In [ ]:
Tips.head(2)

total_bill   tip     sex smoker  day    time  size  tips_10perc_inc
0       16.99  1.01  Female     No  Sun  Dinner     2            1.111
1       10.34  1.66    Male     No  Sun  Dinner     3            1.826

In [ ]:
Tips_copy.head(2)

total_bill   tip     sex smoker  day    time  size  tips_10perc_inc
0       16.99  1.01  Female     No  Sun  Dinner     2            1.111
1       10.34  1.66    Male     No  Sun  Dinner     3            1.826

In [ ]:
Tips_shallowcopy['tips_10perc_inc'] = Tips_shallowcopy['tip']*1.5

In [ ]:
Tips_shallowcopy.head(2)

total_bill   tip     sex smoker  day    time  size  tips_10perc_inc
0       16.99  1.01  Female     No  Sun  Dinner     2            1.515
1       10.34  1.66    Male     No  Sun  Dinner     3            2.490

In [ ]:
Tips_deepcopy.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
# To iterate over rows of a data frame
# iter corresponds to the rows number of the dataframe
# row correspond the values of the row number
for iter, row in Tips.head(2).iterrows():
  print(iter)
  print(row)
  print("Tip value for the row is:",row["tip"])  # to extract value of the column for that row

0
total_bill          16.99
tip                  1.01
sex                Female
smoker                 No
day                   Sun
time               Dinner
size                    2
tips_10perc_inc     1.111
Name: 0, dtype: object
Tip value for the row is: 1.01
1
total_bill          10.34
tip                  1.66
sex                  Male
smoker                 No
day                   Sun
time               Dinner
size                    3
tips_10perc_inc     1.826
Name: 1, dtype: object
Tip value for the row is: 1.66


In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated


In [ ]:
# Extracting data from Big Query - https://colab.research.google.com/notebooks/bigquery.ipynb#scrollTo=DMxOKQ3vJplj
%%bigquery --project ml-tensorflow-coursera9 TaxiTrips
SELECT * 
FROM `bigquery-public-data.new_york_taxi_trips.tlc_fhv_trips_2016` # TODO 1
LIMIT 10

In [ ]:
TaxiTrips.head()

location_id     pickup_datetime  ...                      zone service_zone
0          227 2016-05-12 10:53:00  ...          Sunset Park East    Boro Zone
1          254 2016-05-27 09:24:00  ...  Williamsbridge/Olinville    Boro Zone
2          213 2016-05-14 13:35:00  ...     Soundview/Castle Hill    Boro Zone
3           35 2016-12-23 12:47:26  ...               Brownsville    Boro Zone
4           41 2016-09-04 04:46:47  ...            Central Harlem    Boro Zone

[5 rows x 6 columns]

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.all.html
# pre-processing using np.all
# Rows that dont satisfy any of the conditions within np.all are removed

def preprocess(df_process):
    Tips = df_process.copy(deep=True)  # Making sure that when preprocess if applied on trips data, original copy of trips is created
    qc = np.all([
        df_process["tip"] >= 1,
        df_process["tip"] <= 5,
        df_process["size"] >= 2,
        df_process["size"] <= 4,
        ], axis=0)

    return df_process[qc]

In [ ]:
Tips_qc = preprocess(Tips)
print(Tips_qc.describe(),"\n")
print(Tips_qc.shape, "of", Tips.shape, " rows remained")

       total_bill         tip        size
count  215.000000  215.000000  215.000000
mean    18.597163    2.714930    2.413953
std      7.545923    0.951029    0.704320
min      5.750000    1.000000    2.000000
25%     13.215000    2.000000    2.000000
50%     16.990000    2.600000    2.000000
75%     21.910000    3.395000    3.000000
max     45.350000    5.000000    4.000000 

(215, 7) of (244, 7)  rows remained


In [ ]:
# Gives out values from 0 to len(Tips_qc)
np.arange(0, len(Tips_qc))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
# Diff between append and extend
features = list(Tips)
features.extend(["X1","X2","X3"])
print(features)
features.append(["X4","X5","X6"])
print(features)

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'X1', 'X2', 'X3']
['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'X1', 'X2', 'X3', ['X4', 'X5', 'X6']]


### Tensorflow

In [ ]:
@tf.function
def f(x):
  if tf.reduce_sum(x) > 0:
    return x * x
  else:
    return -x // 2
f(tf.constant(-2))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.constant(np.random.randint(low=0, high=100, size=50))

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 90, 77,  0,  6, 92, 92, 39, 86, 52, 56, 48, 41, 31, 30, 16, 53,
       24, 13, 16, 45, 80, 86, 89, 83, 15, 95,  8, 75, 19, 93, 41, 89, 44,
       22, 96, 23, 51, 54, 27, 71,  9, 95, 93, 71, 90, 93, 77,  9, 58])>

In [ ]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.14461532, 0.47998683, 0.05242564, 0.00252278, 0.72190747,
       0.85516836, 0.78986885, 0.05670708, 0.45445711, 0.22701807,
       0.35241043, 0.11043303, 0.85949368, 0.64855534, 0.56846399,
       0.6087659 , 0.7441141 , 0.43281527, 0.01802605, 0.03769644,
       0.8536098 , 0.14645528, 0.9124743 , 0.84914022, 0.84202672,
       0.90937323, 0.42958974, 0.83355397, 0.74647532, 0.19296946,
       0.70388297, 0.75868233, 0.12808828, 0.61737789, 0.76893558,
       0.87983249, 0.71547245, 0.76292438, 0.4222632 , 0.93577446,
       0.21723343, 0.26656408, 0.10292476, 0.69702024, 0.08587017,
       0.43696642, 0.29125902, 0.62991896, 0.34842642, 0.94315404])>

In [ ]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

In [ ]:
tf.zeros([3, 2, 4, 5])

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
Ones_matrix = tf.ones([4, 5])
Ones_matrix

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Tensorflow Indexing

In [ ]:
print("Type of every element:", Ones_matrix.dtype)
print("Number of dimensions:", Ones_matrix.ndim)
print("Shape of tensor:", Ones_matrix.shape)
print("Elements along axis 0 of tensor:", Ones_matrix.shape[0])
print("Elements along the last axis of tensor:", Ones_matrix.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(Ones_matrix).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 2
Shape of tensor: (4, 5)
Elements along axis 0 of tensor: 4
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  20


In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

# When tensors are Indexed with a scalar, it removes the dimension
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
# When tensors are Indexed with a `:` slice keeps the dimension
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6],
                             [7, 8]], dtype=tf.int32)
print(rank_2_tensor)

# Indexed tensors using any combination integers and slices `:`
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy(),"\n")
print("Second column:", rank_2_tensor[:, 1].numpy(),"\n")
print("Last row:", rank_2_tensor[-1, :].numpy(),"\n")
print("First item in last column:", rank_2_tensor[0, -1].numpy(),"\n")
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Second row: [3 4] 

Second column: [2 4 6 8] 

Last row: [7 8] 

First item in last column: 2 

Skip the first row:
[[3 4]
 [5 6]
 [7 8]] 



### Reshape & Transpose

In [ ]:
print(rank_2_tensor,"\n")
print(tf.reshape(rank_2_tensor, [8]),"\n")  # 6,1
print(tf.reshape(rank_2_tensor, [2,4]),"\n")
print(tf.reshape(rank_2_tensor, [2,2,2]),"\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32) 

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32) 

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) 



In [ ]:
print(rank_2_tensor,"\n")
print(tf.reshape(rank_2_tensor, [8]),"\n")  # 8,1 ==> 8 rows, 1 column
print(tf.reshape(rank_2_tensor, [2,4]),"\n")
print(tf.reshape(rank_2_tensor, [2,2,2]),"\n")
print(tf.reshape(rank_2_tensor, [-1]),"\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32) 

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32) 

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) 

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 



In [ ]:
print(rank_2_tensor,"\n")
print("Transposes","\n") # Transpose coverts row into column, column into row
print(tf.transpose(rank_2_tensor),"\n")
print(tf.transpose(tf.reshape(rank_2_tensor, [8])),"\n")  # Not transposing as a column
print(tf.transpose(tf.reshape(rank_2_tensor, [2,4])),"\n")
print(tf.transpose(tf.reshape(rank_2_tensor, [2,2,2])),"\n")
print(tf.transpose(tf.reshape(rank_2_tensor, [-1])),"\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32) 

Transposes 

tf.Tensor(
[[1 3 5 7]
 [2 4 6 8]], shape=(2, 4), dtype=int32) 

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 

tf.Tensor([[1 2 3 4 5 6 7 8]], shape=(1, 8), dtype=int32) 

tf.Tensor(
[[1 5]
 [2 6]
 [3 7]
 [4 8]], shape=(4, 2), dtype=int32) 

tf.Tensor(
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]], shape=(2, 2, 2), dtype=int32) 

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 



In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor, "\n")
print(tf.reshape(rank_3_tensor, [-1]), "\n")
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]), "\n")  # shape=(3, 10) ==> -1 is automatic

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32) 

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32) 



In [ ]:
# `tf.cast` casts a tensor to a new data type.
# TODO 2b
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, let's cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


In [ ]:
# [1,3] shaped tensor is converted to [3,3] shape
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [ ]:
# We can use split to split a string into a set of tensors
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor(b'Gray wolf', shape=(), dtype=string)
tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [ ]:
# If we have two string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (2,), indicating that it is 2 x unknown.
print(tensor_of_strings)
print(tf.strings.split(tensor_of_strings))

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [ ]:
x = tf.Variable(5.6)

# The .assign() method will assign the value to referance object.
x.assign(45.8)
print(x)

# The .assign_add() method will update the referance object by adding value to it.
x.assign_add(4)
print(x)

# The .assign_add() method will update the referance object by subtracting value to it.
x.assign_sub(3) 
print(x)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.8>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=49.8>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=46.8>


In [ ]:
# Creates a constant tensor from a tensor-like object.
a = tf.constant([5, 3, 8]) # TODO 1a
b = tf.constant([3, -1, 2])
# Using the .add() method components of a tensor will be added.
print(tf.add(a, b))

# Using the .multiply() method components of a tensor will be multiplied.
print(tf.multiply(a, b))

# tf.math.exp expects floats so we need to explicitly give the type
# tf.math.exp(a)

tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)
tf.Tensor([15 -3 16], shape=(3,), dtype=int32)


### Load Data with tf.data
https://colab.research.google.com/github/adammichaelwood/tf-docs/blob/csv-feature-columns/site/en/r2/tutorials/load_data/csv.ipynb#scrollTo=tSyrkSQwYHKi

In [ ]:
# get_dataset() retrieve a Dataverse dataset or its metadata
def get_dataset(file_path, **kwargs):
 # TODO 2 
 # Use `tf.data.experimental.make_csv_dataset()` to read CSV files into a dataset.
  dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=5, # Artificially small to make examples easier to show.
      label_name=LABEL_COLUMN,
      na_value="?",
      num_epochs=1,
      ignore_errors=True, 
      **kwargs)
  return dataset

raw_train_data = get_dataset(train_file_path)
raw_test_data = get_dataset(test_file_path)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, -3, 16], dtype=int32)>

### tf.feature_column 
https://www.tensorflow.org/api_docs/python/tf/feature_column

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/feat.cols_tf.data.ipynb


In [ ]:
# Normalize numeric data
tf.feature_column.numeric_column('numeric', normalizer_fn=normalizer, shape=[len(NUMERIC_FEATURES)])

# `tf.keras.layers.DenseFeatures()` produces a dense Tensor based on given feature_columns.
tf.keras.layers.DenseFeatures(numeric_columns)

# `tf.keras.layers.DenseFeatures()` produces a dense Tensor based on given feature_columns.
numeric_layer = tf.keras.layers.DenseFeatures(numeric_columns)
numeric_layer(example_batch).numpy()

In [ ]:
# processing categorical columns - https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/load_diff_filedata.ipynb
# `tf.keras.layers.DenseFeatures()` produces a dense Tensor based on given feature_columns.
categorical_layer = tf.keras.layers.DenseFeatures(categorical_columns)

# Add the two feature column collections
# Pass them to a `tf.keras.layers.DenseFeatures()` to create an input layer.
# TODO 1
preprocessing_layer = tf.keras.layers.DenseFeatures(categorical_columns+numeric_columns)

In [ ]:
# Similar to one-hot encoding for that ranges of values
age_buckets = tf.feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])

tf.feature_column.categorical_column_with_vocabulary_list('Var', ['Cat1', 'Cat2', 'Cat3'])

tf.feature_column.embedding_column(Var, dimension=8)

### Read and write data using TFRecords 
* tf.train.Example 
* tf.train.SequenceExample

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/tfrecord-tf.example.ipynb

### TensorFlow Dataset API
* tf.data to read the CSV files
*  tf.data.experimental.make_batched_features_dataset to read TFRecords

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/2_dataset_api.ipynb

In [ ]:
# Varibles for the function in the next cell
# Defining the feature names into a list `CSV_COLUMNS`
CSV_COLUMNS = [
    'fare_amount',
    'pickup_datetime',
    'pickup_longitude',
    'pickup_latitude',
    'dropoff_longitude',
    'dropoff_latitude',
    'passenger_count',
    'key'
]
LABEL_COLUMN = 'fare_amount'
# Defining the default values into a list `DEFAULTS`
DEFAULTS = [[0.0], ['na'], [0.0], [0.0], [0.0], [0.0], [0.0], ['na']]

UNWANTED_COLS = ['pickup_datetime', 'key']
# Let's define the features_and_labels() method
# TODO 4a
def features_and_labels(row_data):
# The .pop() method will return item and drop from frame. 
    label = row_data.pop(LABEL_COLUMN)
    features = row_data
    
    for unwanted_col in UNWANTED_COLS:
        features.pop(unwanted_col)

    return features, label

In [8]:
def create_dataset(path_of_data, batch_size, mode):
# The tf.data.experimental.make_csv_dataset() method reads CSV files into a dataset
    dataset = tf.data.experimental.make_csv_dataset(
        pattern, batch_size, CSV_COLUMNS, DEFAULTS)

# The map() function executes a specified function for each item in an iterable.
# The item is sent to the function as a parameter.
    dataset = dataset.map(features_and_labels).cache()

    if mode == "train":
        dataset = dataset.shuffle(1000).repeat()

    # take advantage of multi-threading; 1=AUTOTUNE
    dataset = dataset.prefetch(1)  # before returning we will want to prefetch 1 data point ahead of time (dataset.prefetch(1)) to speed-up training:
    return dataset

In [ ]:
# Path of various locations
#  ../data/taxi-test.csv
#  ../data/taxi-train.csv
#  ../data/taxi-valid.csv

create_dataset('../data/taxi-train*',2,mode="train")
create_dataset('../data/taxi-valid*',2,mode="eval")
create_dataset('../data/taxi-test*',2,mode="test")

### Feature Analysis Using TensorFlow Data Validation and Facets

In [ ]:
# Fairness Indicators is designed to support in evaluating, improving, and comparing models for fairness concerns.
!pip3 install fairness-indicators==0.1.2 --user

In [1]:
# The import statement combines two operations; it searches for the named module, then it binds the results of that search
# to a name in the local scope.
# %tensorflow_version 2.x
import sys, os
import warnings
warnings.filterwarnings('ignore')
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Ignore deprecation warnings
import tempfile
import apache_beam as beam
import numpy as np
import pandas as pd
from datetime import datetime

import tensorflow_hub as hub
import tensorflow as tf
import tensorflow_model_analysis as tfma
import tensorflow_data_validation as tfdv
from tensorflow_model_analysis.addons.fairness.post_export_metrics import fairness_indicators
from tensorflow_model_analysis.addons.fairness.view import widget_view
from fairness_indicators.examples import util

import warnings
warnings.filterwarnings("ignore")

from witwidget.notebook.visualization import WitConfigBuilder
from witwidget.notebook.visualization import WitWidget


print(tf.version.VERSION) 
print(tf) # This statement shows us what version of Python we are currently running.

2.4.1
<module 'tensorflow' from '/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py'>


In [2]:
download_original_data = False #@param {type:"boolean"}


# TODO 1

# Downloads a file from a URL if it is not already in the cache using the `tf.keras.utils.get_file()` function.
if download_original_data:
  train_tf_file = tf.keras.utils.get_file('train_tf.tfrecord',
                                          'https://storage.googleapis.com/civil_comments_dataset/train_tf.tfrecord')
  validate_tf_file = tf.keras.utils.get_file('validate_tf.tfrecord',
                                             'https://storage.googleapis.com/civil_comments_dataset/validate_tf.tfrecord')

  # The identity terms list will be grouped together by their categories
  # (see 'IDENTITY_COLUMNS') on threshould 0.5. Only the identity term column,
  # text column and label column will be kept after processing.
  train_tf_file = util.convert_comments_data(train_tf_file)
  validate_tf_file = util.convert_comments_data(validate_tf_file)

# TODO 1a

else:
  train_tf_file = tf.keras.utils.get_file('train_tf_processed.tfrecord',
                                          'https://storage.googleapis.com/civil_comments_dataset/train_tf_processed.tfrecord')
  validate_tf_file = tf.keras.utils.get_file('validate_tf_processed.tfrecord',
                                             'https://storage.googleapis.com/civil_comments_dataset/validate_tf_processed.tfrecord')

324943872/324941336 [==============================] - 3s 0us/step


In [4]:
# The computation of statistics using TFDV.  The returned value is a DatasetFeatureStatisticsList protocol buffer. 
stats = tfdv.generate_statistics_from_tfrecord(data_location=train_tf_file)

# A visualization of the statistics using Facets Overview.
tfdv.visualize_statistics(stats)

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


In [5]:
#@title Calculate label distribution for gender-related examples
raw_dataset = tf.data.TFRecordDataset(train_tf_file)

toxic_gender_examples = 0
nontoxic_gender_examples = 0

# TODO 4

# There are 1,082,924 examples in the dataset
# The `take()` method returns the specified number of elements starting from the first element.
for raw_record in raw_dataset.take(1082924):
  example = tf.train.Example()
  example.ParseFromString(raw_record.numpy())
  if str(example.features.feature["gender"].bytes_list.value) != "[]":
    if str(example.features.feature["toxicity"].float_list.value) == "[1.0]":
      toxic_gender_examples += 1
    else:
      nontoxic_gender_examples += 1

# TODO 4a

print("Toxic Gender Examples: %s" % toxic_gender_examples)
print("Nontoxic Gender Examples: %s" % nontoxic_gender_examples)

Toxic Gender Examples: 7189
Nontoxic Gender Examples: 41572
